In [1]:
import tensorflow as tf

In [2]:
import numpy as np 
import pandas as pd

In [3]:
df=pd.read_csv("spam.csv", encoding='latin-1')

In [4]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [5]:
df.drop(["Unnamed: 2","Unnamed: 3","Unnamed: 4"],axis=1,inplace=True)

In [6]:
df.shape

(5572, 2)

In [7]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
X=df.drop("v1",axis=1)

In [9]:
X.head()

v2
0  Go until jurong point, crazy.. Available only ...
1                      Ok lar... Joking wif u oni...
2  Free entry in 2 a wkly comp to win FA Cup fina...
3  U dun say so early hor... U c already then say...
4  Nah I don't think he goes to usf, he lives aro...

In [10]:
y=df["v1"]

In [11]:
y

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: v1, Length: 5572, dtype: object

In [12]:
y= pd.get_dummies(df['v1'],drop_first=True)

In [13]:
y

spam
0        0
1        0
2        1
3        0
4        0
...    ...
5567     1
5568     0
5569     0
5570     0
5571     0

[5572 rows x 1 columns]

In [14]:
y.head()

spam
0     0
1     0
2     1
3     0
4     0

In [15]:
import tensorflow as tf

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [17]:
voc_size=50000

In [18]:
messages=X.copy()

In [19]:
messages.head()

v2
0  Go until jurong point, crazy.. Available only ...
1                      Ok lar... Joking wif u oni...
2  Free entry in 2 a wkly comp to win FA Cup fina...
3  U dun say so early hor... U c already then say...
4  Nah I don't think he goes to usf, he lives aro...

In [20]:
import nltk
import re
from nltk.corpus import stopwords

In [21]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lalith\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [22]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    
    review = re.sub('[^a-zA-Z]', ' ', messages['v2'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [23]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [24]:
onehot_repr=[one_hot(word,voc_size) for word in corpus]
onehot_repr

[[39059,
  11520,
  28351,
  1747,
  38696,
  7372,
  49365,
  28162,
  46152,
  16854,
  32260,
  8531,
  15092,
  9769,
  7946,
  20384],
 [12065, 14742, 11721, 26394, 7329, 42783],
 [6124,
  46942,
  7105,
  41418,
  33770,
  34838,
  39212,
  6220,
  39987,
  11000,
  48987,
  48174,
  34838,
  42046,
  46942,
  6054,
  49961,
  33015,
  10521,
  35655,
  31097],
 [7329, 6270, 23777, 20218, 40391, 7329, 35655, 17073, 23777],
 [8687, 32154, 1357, 49872, 49080, 10560, 30176],
 [12776,
  12407,
  19062,
  29894,
  36919,
  23362,
  7441,
  772,
  46799,
  9758,
  12065,
  2722,
  49961,
  19851,
  41158,
  14031],
 [29037, 5856, 7441, 46495, 24047, 7441, 38518, 7138],
 [8301,
  18680,
  29786,
  29786,
  35100,
  4077,
  48690,
  48059,
  48336,
  13921,
  40012,
  30160,
  18992,
  48248,
  13921],
 [12835,
  30455,
  32980,
  43746,
  10046,
  43223,
  18143,
  39843,
  3985,
  8504,
  3985,
  46277,
  23946,
  73,
  31632],
 [13481,
  4167,
  7329,
  34539,
  31023,
  25120,
  815,

In [25]:
sent_length=50
embedded_docs=pad_sequences(onehot_repr,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[    0     0     0 ...  9769  7946 20384]
 [    0     0     0 ... 26394  7329 42783]
 [    0     0     0 ... 10521 35655 31097]
 ...
 [    0     0     0 ... 34411   283 46442]
 [    0     0     0 ... 16051 43544  6124]
 [    0     0     0 ... 49738 36451  4713]]


In [26]:
from tensorflow.keras.layers import Bidirectional
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add((LSTM(100)))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 50, 40)            2000000   
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 2,056,501
Trainable params: 2,056,501
Non-trainable params: 0
_________________________________________________________________
None


In [27]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)


In [28]:
## train test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final,y_final, test_size=0.33, random_state=42)

In [29]:
X_train

array([[    0,     0,     0, ..., 12491, 38915, 22321],
       [    0,     0,     0, ..., 47724, 15988, 34048],
       [    0,     0,     0, ..., 25454, 17183,  3933],
       ...,
       [    0,     0,     0, ..., 45878,   258, 22664],
       [    0,     0,     0, ..., 11721, 19803, 29909],
       [    0,     0,     0, ...,  1951, 39059, 13162]])

In [30]:
X_test

array([[    0,     0,     0, ...,  8938, 27629, 32296],
       [    0,     0,     0, ..., 36876, 20302, 23243],
       [    0,     0,     0, ..., 31119,  5989, 47795],
       ...,
       [    0,     0,     0, ...,  6702, 24059,  5621],
       [    0,     0,     0, ...,     0, 23721, 11882],
       [    0,     0,     0, ..., 49686, 33015,  4059]])

In [31]:
y_train

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=uint8)

In [32]:
y_test

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [1]], dtype=uint8)

In [33]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=32)

Epoch 1/10
117/117 [==============================] - 19s 119ms/step - loss: 0.2399 - accuracy: 0.9242 - val_loss: 0.0683 - val_accuracy: 0.9826
Epoch 2/10
117/117 [==============================] - 13s 112ms/step - loss: 0.0390 - accuracy: 0.9869 - val_loss: 0.0498 - val_accuracy: 0.9864
Epoch 3/10
117/117 [==============================] - 14s 116ms/step - loss: 0.0303 - accuracy: 0.9906 - val_loss: 0.0610 - val_accuracy: 0.9859
Epoch 4/10
117/117 [==============================] - 13s 113ms/step - loss: 0.0146 - accuracy: 0.9962 - val_loss: 0.0450 - val_accuracy: 0.9897
Epoch 5/10
117/117 [==============================] - 13s 112ms/step - loss: 0.0052 - accuracy: 0.9989 - val_loss: 0.0607 - val_accuracy: 0.9869
Epoch 6/10
117/117 [==============================] - 13s 110ms/step - loss: 0.0023 - accuracy: 0.9992 - val_loss: 0.0669 - val_accuracy: 0.9875
Epoch 7/10
117/117 [==============================] - 13s 109ms/step - loss: 0.0021 - accuracy: 0.9997 - val_loss: 0.0629 - val_ac

In [34]:
# Save the trained model
model.save('spam_ham_classifier.h5')
from tensorflow.keras.models import load_model

# Load the saved model
loaded_model = load_model('spam_ham_classifier.h5')


In [35]:
y_pred=model.predict(X_test)

58/58 [==============================] - 2s 26ms/step


In [36]:
y_pred=np.where(y_pred>=0.5,1,0)

In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)

array([[1587,    0],
       [  22,  230]], dtype=int64)

In [38]:
print(accuracy_score(y_test,y_pred))

0.988036976617727


In [39]:
# Function to Predict New Messages
def predict_message(message, model, voc_size, sent_length):
    ps = PorterStemmer()
    review = re.sub('[^a-zA-Z]', ' ', message)
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    onehot_repr = [one_hot(review, voc_size)]
    embedded_docs = pad_sequences(onehot_repr, padding="pre", maxlen=sent_length)
    prediction = model.predict(embedded_docs)
    return 'spam' if prediction >= 0.5 else 'ham'

# Example Prediction
user_input = input("Enter a message to check if it's spam or ham: ")
result = predict_message(user_input, model, voc_size, sent_length)
print(f"The message is: {result}")

Enter a message to check if it's spam or ham: you won car!!!!!!!!!
1/1 [==============================] - 0s 89ms/step
The message is: ham
